/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.movies;

/**
 *
 * @author hasssan
 */
public class Home extends javax.swing.JFrame {

    private DatabaseConnection db;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setupMovieTable();
        initializeDatabase();
        setTitle("Movie Database");
    }
    private void initializeDatabase() {
    try {
        db = new DatabaseConnection();
        System.out.println("Database connected successfully!");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Database connection failed: " + e.getMessage() + 
            "\nMake sure movies.db is in your project root folder.", "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

    private void setupMovieTable() {
        // Create dynamic table model with 0 initial rows
        String[] columns = {"Title", "Year", "Rating", "Votes", "Directors", "Stars"};
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make table read-only
            }
        };

        // Set the dynamic model to your table
        jTable1.setModel(model);

        // Set proper column widths
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(200); // Title
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(60);  // Year
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);  // Rating
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100); // Votes
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(150); // Directors
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(200); // Stars

        // Enable sorting - users can click column headers to sort
        jTable1.setAutoCreateRowSorter(true);
    }

private void displayMovies(java.util.List movies) {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear existing data
    
    for (int i = 0; i < movies.size(); i++) {
        Movie movie = (Movie) movies.get(i); // Cast to Movie
        model.addRow(new Object[]{
            movie.getTitle(),
            movie.getYear(),
            movie.getRating(),
            movie.getVotes(),
            movie.getDirectors(),
            movie.getStars()
        });
    }
    
    // Show result count in window title
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_field_search = new javax.swing.JTextField();
        cbx_search_by = new javax.swing.JComboBox<>();
        btn_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_star_insights = new javax.swing.JButton();
        btn_director_insights1 = new javax.swing.JButton();
        btn_year_insights = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Search by");

        txt_field_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_field_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_field_searchActionPerformed(evt);
            }
        });

        cbx_search_by.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title", "Year", "Rating", "Votes", "Directors", "Stars" }));

        btn_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_star_insights.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_star_insights.setText("Star Insights");
        btn_star_insights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_star_insightsActionPerformed(evt);
            }
        });

        btn_director_insights1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_director_insights1.setText("Director Insights");
        btn_director_insights1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_director_insights1ActionPerformed(evt);
            }
        });

        btn_year_insights.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_year_insights.setText("Year Insights");
        btn_year_insights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_year_insightsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_field_search, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbx_search_by, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_year_insights)
                        .addGap(18, 18, 18)
                        .addComponent(btn_star_insights)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_director_insights1)))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_director_insights1)
                        .addComponent(btn_star_insights)
                        .addComponent(btn_year_insights))
                    .addComponent(cbx_search_by)
                    .addComponent(txt_field_search))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        try {
            String searchTerm = txt_field_search.getText().trim();
            String searchBy = (String) cbx_search_by.getSelectedItem();
            
            java.util.List movies;
            
            if (searchTerm.isEmpty()) {
                // If search is empty, show all movies
                movies = db.getAllMovies();
            } else {
                // Search with term
                movies = db.searchMovies(searchTerm, searchBy);
            }
            
            displayMovies(movies);
            
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Search error: " + ex.getMessage(), "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_field_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_field_searchActionPerformed
        // TODO add your handling code here:
        btn_searchActionPerformed(evt);
    }//GEN-LAST:event_txt_field_searchActionPerformed

    private void btn_star_insightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_star_insightsActionPerformed
        // TODO add your handling code here:
        String searchBy = (String) cbx_search_by.getSelectedItem();
        String searchTerm = txt_field_search.getText().trim();

        // Check if user is searching by Stars
        if (searchBy.equals("Stars") && !searchTerm.isEmpty()) {
            try {
                // Open StarInsights with the searched actor name
                StarInsights starFrame = new StarInsights(searchTerm);
                starFrame.setVisible(true);

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error opening Star Insights: " + e.getMessage(), "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Not searching by stars or empty search - ask for actor name
            javax.swing.JOptionPane.showMessageDialog(this, 
                "To see Star Insights:\n\n" +
                "1. Select 'Stars' from the Search By dropdown\n" +
                "2. Enter an actor name in the search box\n" +
                "3. Click Star Insights button\n\n" +
                "Or you can search for movies by actor first.", 
                "How to Use Star Insights", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    
    }//GEN-LAST:event_btn_star_insightsActionPerformed

    private void btn_director_insights1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_director_insights1ActionPerformed
        // TODO add your handling code here:
        String searchBy = (String) cbx_search_by.getSelectedItem();
        String searchTerm = txt_field_search.getText().trim();

        // Check if user is searching by Directors
        if (searchBy.equals("Directors") && !searchTerm.isEmpty()) {
            try {
                // Open DirectorInsights with the searched director name
                DirectorInsights directorFrame = new DirectorInsights(searchTerm);
                directorFrame.setVisible(true);

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error opening Director Insights: " + e.getMessage(), "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Not searching by directors or empty search - ask for director name
            javax.swing.JOptionPane.showMessageDialog(this, 
                "To see Director Insights:\n\n" +
                "1. Select 'Directors' from the Search By dropdown\n" +
                "2. Enter a director name in the search box\n" +
                "3. Click Director Insights button\n\n" +
                "Or you can search for movies by director first.", 
                "How to Use Director Insights", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_director_insights1ActionPerformed

    private void btn_year_insightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_year_insightsActionPerformed
        // TODO add your handling code here:
        String searchBy = (String) cbx_search_by.getSelectedItem();
        String searchTerm = txt_field_search.getText().trim();

        // Check if user is searching by Year
        if (searchBy.equals("Year") && !searchTerm.isEmpty()) {
            try {
                // Use the year from search box
                int year = Integer.parseInt(searchTerm);
                YearInsights yearFrame = new YearInsights(year);
                yearFrame.setVisible(true);

            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Please enter a valid year number in the search box.", "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Not searching by year or empty search - ask for year
            javax.swing.JOptionPane.showMessageDialog(this, 
                "To see Year Insights:\n\n" +
                "1. Select 'Year' from the Search By dropdown\n" +
                "2. Enter a year in the search box\n" +
                "3. Click Year Insights button\n\n" +
                "Or you can search for movies from a year first.", 
                "How to Use Year Insights", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_year_insightsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_director_insights1;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_star_insights;
    private javax.swing.JButton btn_year_insights;
    private javax.swing.JComboBox<String> cbx_search_by;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_field_search;
    // End of variables declaration//GEN-END:variables
}
